spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/oficina-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      data-locations: ${SQL_DATA_LOCATIONS:classpath:import.sql}

jwt:
  secret: ${JWT_SECRET:minha-chave-super-secreta-para-jwt-256-bits}
  expiration-in-ms: ${JWT_EXPIRATION:14400000}

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
